---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Diana Wolf"
title: "bibliothek am meer"
pdf: "../master.pdf"
date: 2018-04-29
comments: false
sharing: true
footer: true

---