---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Beate Detlefs"
title: "Patientenbibliothek am Campus Charité Mitte"
pdf: "../master.pdf"
date: 2018-04-28
comments: false
sharing: true
footer: true

---