---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Jana Rumler"
title: "Bibliothek des Leibniz-Zentrums für Agrarlandschaftsforschung (ZALF) e.V."
pdf: "../master.pdf"
date: 2018-04-29
comments: false
sharing: true
footer: true

---