---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Swantje Dogunke"
- "Timo Steyer"
- "Corinna Mayer"
title: "Barcamp Data and Demons: von Bestands- und Forschungsdaten zu Services"
subtitle: "Treffen sich ein Bibliothekar, eine Archäologin, ein Informatiker, …"
pdf: "master.pdf"
date: 2018-04-19 22:00
comments: false
sharing: true
footer: true

---