---

layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Karen Bordonaro"
- "Shelby Angalik"
title: "Libraries and the Arctic: Language Education Support"
pdf: "master.pdf"
date: 2018-05-04
comments: false
sharing: true
footer: true

---