---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Steffi Hotze"
title: "Menschen – Bücher – Wissenssuche"
subtitle: "Eine Woche in der UB Erlangen-Nürnberg (20. November – 24. November 2017)"
pdf: "master.pdf"
date: 2018-05-04
comments: false
sharing: true
footer: true

---